# Generated by Django 3.2.25 on 2026-09-27 04:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(choices=[('PDF', 'PDF'), ('SLIDESHOW', 'Slideshow'), ('VIDEO', 'Video')], default='VIDEO', max_length=20)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RENDERING', 'Rendering'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('output_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('transition_style', models.CharField(blank=True, default='crossfade', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='stories.project')),
            ],
        ),
    ]
