# Generated by Django 5.2.17 on 2026-09-27 07:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=1)),
                ('page_number', models.CharField(default='01', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('layout_mode', models.CharField(choices=[('single_panel', 'Single Panel'), ('multi_panel', 'Multi Panel'), ('storyboard', 'Storyboard')], default='single_panel', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATING', 'Generating'), ('OPTIONS_READY', 'Options Ready'), ('REFINING', 'Refining'), ('APPROVED', 'Approved')], default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='stories.project')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('panel_index', models.IntegerField(default=0)),
                ('scene_json', models.JSONField(default=dict)),
                ('compiled_prompt', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='pages.page')),
            ],
            options={
                'ordering': ['panel_index'],
            },
        ),
        migrations.CreateModel(
            name='PanelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(default=1)),
                ('prompt_used', models.TextField()),
                ('image_url', models.CharField(blank=True, default='', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='pages.panel')),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='pages.panelversion')),
            ],
            options={
                'ordering': ['version_number'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_index', models.IntegerField(default=0)),
                ('image_url', models.CharField(max_length=1024)),
                ('seed', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('panel_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='pages.panelversion')),
            ],
            options={
                'ordering': ['option_index'],
            },
        ),
    ]
