# Generated by Django 3.2.25 on 2026-09-27 04:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('element_type', models.CharField(choices=[('SPEECH_BUBBLE', 'Speech Bubble'), ('CAPTION', 'Caption'), ('THOUGHT_BUBBLE', 'Thought Bubble'), ('SFX', 'Sound Effect')], default='SPEECH_BUBBLE', max_length=30)),
                ('text', models.TextField(blank=True, default='')),
                ('x_percent', models.FloatField(default=10.0)),
                ('y_percent', models.FloatField(default=10.0)),
                ('width_percent', models.FloatField(default=30.0)),
                ('height_percent', models.FloatField(default=20.0)),
                ('tail_x_percent', models.FloatField(blank=True, null=True)),
                ('tail_y_percent', models.FloatField(blank=True, null=True)),
                ('font_size', models.IntegerField(default=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_elements', to='pages.panel')),
            ],
        ),
    ]
