# Generated by Django 5.1.15 on 2026-10-04 04:52

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.CustomUserManager()),
            ],
        ),
    ]
