# Generated by Django 5.1.15 on 2026-10-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generationjob',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('FAILED_RETRYABLE', 'Failed Retryable'), ('FAILED_FINAL', 'Failed Final'), ('DONE', 'Done'), ('PENDING', 'Pending'), ('EXTRACTING', 'Extracting'), ('COMPILING', 'Compiling'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=30),
        ),
    ]
