# Generated by Django 3.2.25 on 2026-09-27 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('story_notes', models.TextField(blank=True, default='')),
                ('historically_grounded', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('SETUP', 'Setup'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete')], default='SETUP', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StyleBible',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('art_style', models.TextField()),
                ('palette', models.JSONField(default=list)),
                ('lighting_default', models.TextField()),
                ('aspect_ratio', models.CharField(default='16:9', max_length=10)),
                ('render_medium', models.TextField(default='Digital Graphic Novel')),
                ('locked_style_prompt_prefix', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='style_bible', to='stories.project')),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('weather', models.CharField(blank=True, default='', max_length=255)),
                ('time_of_day', models.CharField(blank=True, default='', max_length=255)),
                ('reference_image_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='stories.project')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, default='', max_length=255)),
                ('age', models.CharField(blank=True, default='', max_length=50)),
                ('appearance', models.TextField()),
                ('uniform', models.TextField()),
                ('hair', models.TextField()),
                ('reference_image_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='stories.project')),
            ],
        ),
    ]
