# Generated by Django 5.1.15 on 2026-10-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='avatar_color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='genre',
            field=models.CharField(blank=True, default='Graphic Novel', max_length=100),
        ),
    ]
