# Generated by Django 5.1.15 on 2026-10-04 08:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_character_avatar_color_project_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sender', models.CharField(choices=[('user', 'User'), ('vizzy', 'Vizzy'), ('system', 'System')], max_length=20)),
                ('message_type', models.CharField(default='text', max_length=30)),
                ('content', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='stories.project')),
            ],
            options={
                'db_table': 'story_chat_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['project', 'created_at'], name='story_chat__project_53b0a0_idx'), models.Index(fields=['project', 'page_id', 'created_at'], name='story_chat__project_adb328_idx')],
            },
        ),
    ]
